### ISSUE TITLE
Not working locally with act

### ISSUE THREAD

**Issue by klarkc** [purescript-contrib/setup-purescript#32]
I am trying to simulate the workflow locally with [act](https://github.com/nektos/act), but I am getting this error:
 
```
[CI/build]   💬  ::debug::finished caching tool
| Cached path /opt/hostedtoolcache/spago/0.20.9/x64, adding to PATH
| Fetching psa
| [command]/usr/bin/sudo npm install -g purescript-psa@0.8.2
| sudo: npm: command not found
```

I tried the [default config](https://github.com/purescript-contrib/setup-purescript#basic), and even adding

```yaml
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'
```

before `uses: purescript-contrib/setup-purescript@main` it still happens.

**Comment by thomashoneyman** [comment]
I haven’t used act before so I’m not sure how to solve this. We use NPM because GitHub’s runners have node by default, and therefore npm; if act doesn’t have that, then you’ll have to install it somehow

**Comment by klarkc** [comment]
I have no idea why, but this works:

```yaml
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: 'npm'

      - run: npm install -g bats
      - run: bats -v
```

The only difference is the missing `sudo` :thinking:  there is a reason for the sudo?
